### ISSUE TITLE
Version label does not match dogu.json version

### ISSUE THREAD

**Issue by robertauer** [cloudogu/gotenberg#3]
https://github.com/cloudogu/gotenberg/blob/10f5d9944d71a867c20637772238be1aa47fbc4e/Dockerfile#L20 does not match https://github.com/cloudogu/gotenberg/blob/develop/dogu.json#L3
This should have been automated by the release process, I don't know why it didn't work.

**Comment by eheimbuch** [comment]
Fixed with recent commits
